version: "3.7"

services:
  shelter-evaluation-database:
    image: mariadb:10.6.4
    container_name: shelter-evaluation-database-prod
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: shelter-evaluation-database-prod
      MARIADB_ROOT_PASSWORD: $DATABASE_ROOT_PASSWORD
      MYSQL_DATABASE: $DATABASE_COLLECTION
      MYSQL_USER: $DATABASE_USER
      MYSQL_PASSWORD: $DATABASE_PASSWORD
    networks:
      - shelter-evaluation-network-database
  shelter-evaluation-gateway:
    build:
      context: ../platform/nginx
      args:
        - BACKEND_HOSTNAME
        - BACKEND_UPSTREAM
        - FRONTEND_HOSTNAME
        - FRONTEND_UPSTREAM
    container_name: shelter-evaluation-gateway-prod
    ports:
      - 80:80
      - 443:443
    environment:
      NGINX_HOST: $GATEWAY_HOST
      NGINX_PORT: 80
    networks:
      - shelter-evaluation-network-gateway
  shelter-evaluation-backend:
    build:
      context: ../../packages
      dockerfile: shelter-evaluation-backend/docker/prod/dockerfile
    container_name: shelter-evaluation-backend-prod
    environment:
      DATABSE_HOST: $DATABASE_HOST
      DATABASE_PORT: $DATABASE_PORT
      DATABASE_USER: $DATABASE_USER
      DATABASE_PASSWORD: $DATABASE_PASSWORD
      DATABASE_COLLECTION: $DATABASE_COLLECTION
      DATABASE_SYNCRHONIZE: $DATABASE_SYNCRHONIZE
      TYPEORM_CONNECTION: mysql
      TYPEORM_HOST: $DATABASE_HOST
      TYPEORM_USERNAME: $DATABASE_USER
      TYPEORM_PASSWORD: $DATABASE_PASSWORD
      TYPEORM_DATABASE: $DATABASE_COLLECTION
      TYPEORM_PORT: $DATABASE_PORT
      TYPEORM_SYNCHRONIZE: $TYPEORM_SYNCHRONIZE
      TYPEORM_LOGGING: $TYPEORM_LOGGING
      TYPEORM_ENTITIES: dist/src/**/*.entity.js
      TYPEORM_ENTITIES_DIR: dist/src/package
      TYPEORM_MIGRATIONS: dist/migration/**/*.js
      TYPEORM_MIGRATIONS_DIR: dist/migration
      AUTH_SECRET_KEY: $AUTH_SECRET_KEY
      AUTH_EXPIRE_IN: $AUTH_EXPIRE_IN
      GATEWAY_HOST: $GATEWAY_HOST
    networks:
      - shelter-evaluation-network-gateway
      - shelter-evaluation-network-database
  shelter-evaluation-frontend:
    build:
      context: ../../packages
      dockerfile: shelter-evaluation-front/docker/prod/dockerfile
    container_name: shelter-evaluation-frontend-prod
    networks:
      - shelter-evaluation-network-gateway

networks: 
  shelter-evaluation-network-gateway:
    driver: bridge
  shelter-evaluation-network-database:
    driver: bridge